.PHONY:average seven convert test square

square:
	-python3 Jack_to_VM_translator.py ./Square/*.jack

convert:
	-python3 Jack_to_VM_translator.py ./ConvertToBin/*.jack

test:
	-python3 Jack_to_VM_translator.py ./Test/Main.jack

average:
	-python3 Jack_to_VM_translator.py ./Average/*.jack

seven:
	-python3 Jack_to_VM_translator.py ./Seven/*.jack

