.PHONY:average seven convert

convert:
	-python3 Jack_to_VM_translator.py ./ConvertToBin/*.jack

average:
	-python3 Jack_to_VM_translator.py ./Average/*.jack

seven:
	-python3 Jack_to_VM_translator.py ./Seven/*.jack

