.PHONY:average seven convert test

convert:
	-python3 Jack_to_VM_translator.py ./ConvertToBin/*.jack

test:
	-python3 Jack_to_VM_translator.py ./Main.jack

average:
	-python3 Jack_to_VM_translator.py ./Average/*.jack

seven:
	-python3 Jack_to_VM_translator.py ./Seven/*.jack

